### ISSUE TITLE
Are we ready to delete the CIL code repository?

### ISSUE THREAD

**Issue by allisonpenko** [Coastal-Imaging-Research-Network/OSU_CIL_code#4]
Is anyone using the full CIL repository? Or can we delete it? We had talked about this earlier and wanted to confirm before I did anything. Please let me know your thoughts.

**Comment by RobHolman** [comment]
I believe that we should remove it.

**Comment by RobHolman** [comment]
I think I answered this (get rid of the CIL repository).  But I�m not sure I @-ed anyone, (although the addressee list looks like i did).

Allison, did you get this?

Rob Holman
SECNAV/CNO Chair in Oceanography

104 Ocean Admin Bldg.
CEOAS-OSU
Corvallis, Oregon, USA 97331-5503
ph: 1-541-737-2914
holman@coas.oregonstate.edu
http://cil-www.coas.oregonstate.edu

**Comment by mpalmsten** [comment]
I got the email from github about it.

**Comment by allisonpenko** [comment]
I did too. Next time you fix an issue, can you just comment on the issue that it is finished and then close it? Thanks!

**Comment by RobHolman** [comment]
So much to learn.

Rob Holman
SECNAV/CNO Chair in Oceanography

104 Ocean Admin Bldg.
CEOAS-OSU
Corvallis, Oregon, USA 97331-5503
ph: 1-541-737-2914
holman@coas.oregonstate.edu
http://cil-www.coas.oregonstate.edu

**Comment by SRHarrison** [comment]
ok... I see the delete button....  I'm going for it....
